/**
 * @copyright Copyright (c) 2026 GUIHO Technologies as represented by Cristóvão GUIHO. All Rights Reserved.
 */

import { readdir } from 'node:fs/promises'
import { relative, resolve } from 'node:path'
import { writeFile } from 'node:fs/promises'
import type { XDocsCliOptions, XDocsFile, XDocsParsedArgs } from '../types.js'
import { loadConfigOrDefaults } from '../config.js'
import { scanProject } from '../discovery.js'
import { buildTree, renderTree } from '../tree.js'
import { stringFlag } from '../flags.js'

/** Run the generate command. */
export const runGenerate = async (options: XDocsCliOptions, parsed: XDocsParsedArgs): Promise<void> => {
  const config = await loadConfigOrDefaults(options)
  const targetPath = parsed.positionals[0] ? resolve(options.cwd, parsed.positionals[0]) : options.cwd
  const outputPath = stringFlag(parsed.flags, 'output')

  const result = await scanProject(config)

  const isProjectScope = targetPath === options.cwd

  let content: string

  if (isProjectScope) {
    content = await generateProjectDoc(config.project.name, result.xdocsFiles, config.cwd)
  } else {
    const relTarget = relative(config.cwd, targetPath)
    const relevantFiles = result.xdocsFiles.filter(
      (f) => f.path.startsWith(targetPath),
    )
    content = await generateModuleDoc(relTarget, relevantFiles, config.cwd, targetPath)
  }

  if (outputPath) {
    await writeFile(resolve(options.cwd, outputPath), content, 'utf8')
    process.stdout.write(`generated: ${outputPath}\n`)
  } else {
    process.stdout.write(content)
  }
}

/** Generate a project-level documentation file. */
const generateProjectDoc = async (projectName: string, xdocsFiles: XDocsFile[], _cwd: string): Promise<string> => {
  const lines: string[] = [
    `# ${projectName}`,
    '',
    '## Project Overview',
    '',
    `This document was generated by xdocs. It describes the full project structure.`,
    '',
  ]

  // Tree
  const tree = buildTree(xdocsFiles)
  lines.push('## Hierarchy', '', '```')
  lines.push(renderTree(tree))
  lines.push('```', '')

  // Modules
  lines.push('## Modules', '')

  for (const file of xdocsFiles) {
    if (!file.metadata) continue
    lines.push(`### ${file.metadata.subject}`, '')
    lines.push(file.metadata.description, '')
    lines.push(`Location: \`${file.relativePath}\``, '')

    const fileEntries = Object.entries(file.metadata.files)
    if (fileEntries.length > 0) {
      lines.push('Files:', '')
      for (const [name, desc] of fileEntries) {
        lines.push(`- \`${name}\`: ${desc}`)
      }
      lines.push('')
    }

    const documentEntries = Object.entries(file.metadata.documents)
    if (documentEntries.length > 0) {
      lines.push('Documents:', '')
      for (const [name, desc] of documentEntries) {
        lines.push(`- \`${name}\`: ${desc}`)
      }
      lines.push('')
    }

    if (file.body.trim()) {
      lines.push(file.body.trim(), '')
    }
  }

  return lines.join('\n')
}

/** Generate a module-level documentation file. */
const generateModuleDoc = async (moduleName: string, xdocsFiles: XDocsFile[], _cwd: string, targetPath: string): Promise<string> => {
  const lines: string[] = [
    `# ${moduleName}`,
    '',
  ]

  // List all files in the target directory
  let dirEntries: string[] = []
  try {
    const entries = await readdir(targetPath)
    dirEntries = entries.filter((e) => !e.startsWith('.'))
  } catch {
    // Directory might not exist
  }

  if (xdocsFiles.length > 0) {
    for (const file of xdocsFiles) {
      if (!file.metadata) continue
      lines.push(`## ${file.metadata.subject}`, '')
      lines.push(file.metadata.description, '')

      const fileEntries = Object.entries(file.metadata.files)
      if (fileEntries.length > 0) {
        lines.push('### Files', '')
        for (const [name, desc] of fileEntries) {
          lines.push(`- \`${name}\`: ${desc}`)
        }
        lines.push('')
      }

      const documentEntries = Object.entries(file.metadata.documents)
      if (documentEntries.length > 0) {
        lines.push('### Documents', '')
        for (const [name, desc] of documentEntries) {
          lines.push(`- \`${name}\`: ${desc}`)
        }
        lines.push('')
      }

      if (file.metadata.children.length > 0) {
        lines.push('### Submodules', '')
        for (const child of file.metadata.children) {
          lines.push(`- ${child}`)
        }
        lines.push('')
      }

      if (file.body.trim()) {
        lines.push(file.body.trim(), '')
      }
    }
  } else {
    lines.push(`No xdocs descriptors found in this directory.`, '')
    lines.push('### Directory contents', '')
    for (const entry of dirEntries) {
      lines.push(`- \`${entry}\``)
    }
    lines.push('')
  }

  return lines.join('\n')
}
