package xdocs

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/CGuiho/xdocs/internal/config"
)

type ListedEntry struct {
	Kind        string `json:"kind"`
	File        string `json:"file"`
	Description string `json:"description"`
	Source      string `json:"source"`
}

func List(scan ScanResult, root, target string) []ListedEntry {
	if target == "" {
		target = root
	} else if !filepath.IsAbs(target) {
		target = filepath.Join(root, target)
	}
	target, _ = filepath.Abs(target)
	result := []ListedEntry{}
	for _, descriptor := range scan.XDocsFiles {
		if descriptor.Metadata == nil || !inScope(descriptor.Path, target) {
			continue
		}
		for name, description := range descriptor.Metadata.Files {
			result = append(result, ListedEntry{"file", name, description, descriptor.RelativePath})
		}
		for name, description := range descriptor.Metadata.Documents {
			result = append(result, ListedEntry{"document", name, description, descriptor.RelativePath})
		}
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].Source != result[j].Source {
			return result[i].Source < result[j].Source
		}
		if result[i].Kind != result[j].Kind {
			return result[i].Kind < result[j].Kind
		}
		return result[i].File < result[j].File
	})
	return result
}

func Generate(cfg config.Config, scan ScanResult, target string) (string, error) {
	targetPath := cfg.CWD
	if target != "" {
		targetPath = target
		if !filepath.IsAbs(targetPath) {
			targetPath = filepath.Join(cfg.CWD, targetPath)
		}
	}
	targetPath, _ = filepath.Abs(targetPath)
	if targetPath == cfg.CWD {
		lines := []string{
			"# " + cfg.Project, "", "## Project Overview", "",
			"This document was generated by xdocs. It describes the full project structure.", "",
			"## Hierarchy", "", "```", RenderTree(BuildTree(scan.XDocsFiles)), "```", "",
			"## Modules", "",
		}
		for _, file := range scan.XDocsFiles {
			if file.Metadata == nil {
				continue
			}
			lines = append(lines, renderDescriptor(file, 3)...)
		}
		return strings.Join(lines, "\n"), nil
	}
	policy, err := newPathPolicy(cfg, targetPath)
	if err != nil {
		return "", err
	}
	lines := []string{"# " + displayTarget(cfg.CWD, targetPath), ""}
	if policy.ignored(targetPath, true) || scanExcludedPath(cfg.CWD, targetPath, cfg.Exclude) {
		lines = append(lines, "Target is ignored by xdocs.", "")
		return strings.Join(lines, "\n"), nil
	}
	found := false
	for _, file := range scan.XDocsFiles {
		if file.Metadata == nil || !inScope(file.Path, targetPath) {
			continue
		}
		found = true
		lines = append(lines, renderDescriptor(file, 2)...)
	}
	if !found {
		lines = append(lines, "No xdocs descriptors found in this directory.", "", "### Directory contents", "")
		entries, err := os.ReadDir(targetPath)
		if err != nil {
			return "", fmt.Errorf("read generate target %s: %w", filepath.ToSlash(targetPath), err)
		}
		for _, entry := range entries {
			if strings.HasPrefix(entry.Name(), ".") || (entry.IsDir() && excluded(entry.Name(), cfg.Exclude)) {
				continue
			}
			if policy.ignored(filepath.Join(targetPath, entry.Name()), entry.IsDir()) {
				continue
			}
			lines = append(lines, "- `"+entry.Name()+"`")
		}
		lines = append(lines, "")
	}
	return strings.Join(lines, "\n"), nil
}

func scanExcludedPath(root, target string, values []string) bool {
	relative, err := filepath.Rel(root, target)
	if err != nil || relative == "." || relative == "" {
		return false
	}
	parts := strings.Split(filepath.Clean(relative), string(filepath.Separator))
	for _, part := range parts {
		if excluded(part, values) {
			return true
		}
	}
	return false
}

func Merge(scan ScanResult, root, target string) (string, int) {
	targetPath := root
	if target != "" {
		targetPath = target
		if !filepath.IsAbs(targetPath) {
			targetPath = filepath.Join(root, targetPath)
		}
	}
	targetPath, _ = filepath.Abs(targetPath)
	var lines []string
	count := 0
	for _, file := range scan.XDocsFiles {
		if !inScope(file.Path, targetPath) {
			continue
		}
		count++
		lines = append(lines, "<!-- source: "+file.RelativePath+" -->")
		if file.Metadata != nil {
			lines = append(lines, renderDescriptor(file, 1)...)
		}
		if strings.TrimSpace(file.Body) != "" {
			lines = append(lines, strings.TrimSpace(file.Body), "")
		}
		lines = append(lines, "---", "")
	}
	return strings.Join(lines, "\n"), count
}

func renderDescriptor(file File, level int) []string {
	metadata := file.Metadata
	if metadata == nil {
		return nil
	}
	prefix := strings.Repeat("#", level)
	lines := []string{prefix + " " + metadata.Subject, "", metadata.Description, ""}
	if len(metadata.Keywords) > 0 {
		quoted := make([]string, len(metadata.Keywords))
		for i, keyword := range metadata.Keywords {
			quoted[i] = "`" + keyword + "`"
		}
		lines = append(lines, "Keywords: "+strings.Join(quoted, ", "), "")
	}
	appendMap := func(title string, values map[string]string) {
		if len(values) == 0 {
			return
		}
		lines = append(lines, strings.Repeat("#", level+1)+" "+title, "")
		keys := make([]string, 0, len(values))
		for key := range values {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			lines = append(lines, fmt.Sprintf("- `%s`: %s", key, values[key]))
		}
		lines = append(lines, "")
	}
	appendMap("Files", metadata.Files)
	appendMap("Documents", metadata.Documents)
	if len(metadata.Children) > 0 {
		lines = append(lines, strings.Repeat("#", level+1)+" Submodules", "")
		for _, child := range metadata.Children {
			lines = append(lines, "- "+child)
		}
		lines = append(lines, "")
	}
	if strings.TrimSpace(file.Body) != "" {
		lines = append(lines, strings.TrimSpace(file.Body), "")
	}
	return lines
}
