schema = 1

[project]
name_source = "package.json"

[version]
scheme = "semver"
source = "package.json"
output = ["package.json", "jsr.json", "git"]
prerelease_id = ""

[package]
path = "package.json"

[jsr]
path = "jsr.json"

[git]
tag_template = "{name}@{version}"
commit = true
push = true
allow_dirty = true
